### ISSUE TITLE
Using tenantID and Secret fails with System.ArgumentException: 'authority' should be in URI format.  (Parameter 'authority')

### ISSUE THREAD

**Issue by RedWingBB** [Azure-Samples/active-directory-dotnetcore-daemon-v2#161]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Set up azure portal for application enabled security
Build example, provide  clientid, tenantid, secret in appsettings.json

### Any log messages given by the failure
We could not retrieve the user's list: Status Code: 0
Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.

 ---> System.ArgumentException: 'authority' should be in URI format.  (Parameter 'authority')
   at Microsoft.Identity.Client.AuthorityInfo.ValidateAndCreateAuthorityUri(String authority, Nullable`1 authorityType)
   at Microsoft.Identity.Client.AuthorityInfo.FromAuthorityUri(String authorityUri, Boolean validateAuthority)
   at Microsoft.Identity.Client.Instance.Authority.CreateAuthority(String authority, Boolean validateAuthority)
   at Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(String authorityUri, Boolean validateAuthority)
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.DefaultAuthorizationHeaderProvider.CreateAuthorizationHeaderForAppAsync(String scopes, AuthorizationHeaderProviderOptions downstreamApiOptions, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.TokenAcquisitionAuthenticationProvider.AuthenticateRequestAsync(HttpRequestMessage request)
   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.GraphServiceUsersCollectionRequest.GetAsync(CancellationToken cancellationToken)
   at daemon_console.Program.Main(String[] _) in C:\Src\Calumet\active-directory-dotnetcore-daemon-v2-master\active-directory-dotnetcore-daemon-v2-master\1-Call-MSGraph\daemon-console\Program.cs:line 40

### Expected/desired behavior
Connect and return a clean result

### OS and Version?
Windows 10, VS 2022

### Versions
>

### Mention any other details that might be useful
Using another approach of POST to 
       "https://login.microsoftonline.com/XXXXXX-tenant-id-XXXX-XXXXXX/oauth2/v2.0/token";
works successfully, and i am able to query for groups using the token

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RedWingBB** [comment]
Unbelievable - a typo in the tenant id, had a trailing space
Corrected and now its working
Thanks for the example

**Comment by jmprieur** [comment]
Thanks for the update, @RedWingBB 
I was going to ask you to share your appsettings.json

@jennyf19 we need to do something to detect the configuration when there is a space .... this happened several times over the past weeks. I wonder if some IDE would have a bug that would transform JSON ?
